---
title: "STA-310 remake data cleaning"
output: pdf_document
date: "2025-03-20"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
# install.packages("glmnet")
# install.packages("caret")
# install.packages("leaps")
library(glmnet)
library(caret)
library(leaps)
```

```{r}
# read dataframe
top100data <- read.csv("top100data.csv")
ranking <- read.csv("rankings.csv")
```

```{r}
# get top 100 ranked schools from the 2025 ranking data that we're predicting for
ranking100 <- ranking %>%
  filter(as.numeric(X2025) <= 100)
```

```{r}
# remove columns that have all same data
all_same_columns <- sapply(top100data, function(x) length(unique(x)) == 1)
data_top100 <- top100data[, !(all_same_columns)] # this gives 2987 variables

# make PS NA before filtering
data_top100[] <- as.data.frame(sapply(data_top100, function(col) ifelse(col == "PS", NA, col)))

# filter out those with all unique values or all same values, besides the id column (UNITID)
id_column <- "UNITID" 

unique_columns <- sapply(data_top100, function(x) length(unique(x)) == nrow(data_top100))

data_top100_filtered <- data_top100[, !(unique_columns & names(data_top100) != id_column)]

# print check that PS is not there
# print(data_top100$ENRL_4YR_TRANS_YR2_RT)

# TODO: for each school, replace missing numeric data with the average value 

# make variables numeric

data_top100 <- data_top100 %>%
  mutate(across(12:ncol(.), as.numeric))

# calculate whole mean

overall_means <- data_top100 %>%
  summarise(across(where(is.numeric), mean, na.rm = TRUE)) %>% 
  as.list()

# add missing values

clean_data_top100 <- data_top100 %>%
  group_by(UNITID) %>%
  mutate(across(where(is.numeric), ~ {
    # if all is na replace with overall means
    if (all(is.na(.))) {
      
      overall_means[[cur_column()]]
    } else {
      # otherwise replace na with group mean
      ifelse(is.na(.), mean(., na.rm = TRUE), .)
    }
  })) %>%
  ungroup()

# remove if all NA or same 
clean_data_top100 <- clean_data_top100[,colSums(is.na(data_top100))<nrow(data_top100)]
clean_data_top100 <- clean_data_top100 %>% 
  select(where(~ n_distinct(.) > 1))


# check NA

# colSums(is.na(clean_data_top100))

```

```{r}
# calculate proportion of NA
missing_proportions <- colMeans(is.na(clean_data_top100))

missing_proportions[missing_proportions != 0]
# filters out variables with given threshold
threshold <- 0
data_top100_filtered <- clean_data_top100[, missing_proportions <= threshold]
```

```{r}
# check if factor
unique(data_top100_filtered$ADMCON7)

# make factors
vars_to_factor <- c(
  "CCBASIC",
  "REGION",
  "LOCALE",
  "CCUGPROF",
  "CCSIZSET",
  "CIP01BACHL",                     
  "CIP03CERT2",                                             
  "CIP04BACHL",                                             
  "CIP05CERT2",                                             
  "CIP09CERT2",                                             
  "CIP10BACHL",                                             
  "CIP11CERT2",                                             
  "CIP11BACHL",                                             
  "CIP13CERT1",                                             
  "CIP13BACHL",                                             
  "CIP14CERT4",                                             
  "CIP15BACHL",                                             
  "CIP16CERT2",                                             
  "CIP19BACHL",                                             
  "CIP22CERT2",                                             
  "CIP23CERT2",                                             
  "CIP24ASSOC",                                             
  "CIP26CERT1",                                             
  "CIP26BACHL",                                             
  "CIP27BACHL",                                             
  "CIP30CERT1",                                             
  "CIP30BACHL",                                             
  "CIP38CERT2",                                             
  "CIP39BACHL",                                             
  "CIP40ASSOC",                                             
  "CIP41BACHL",                                             
  "CIP42ASSOC",                                             
  "CIP43BACHL",                                             
  "CIP45CERT1",                                             
  "CIP45BACHL",                                             
  "CIP50ASSOC",                                             
  "CIP50BACHL",                                             
  "CIP51BACHL",                                             
  "CIP52CERT2",                                             
  "CIP52CERT4",                                             
  "CIP54CERT2",
  "CIP03BACHL",
  "CIP05CERT1",
  "CIP05BACHL",
  "CIP09BACHL",
  "CIP11CERT1",
  "CIP11ASSOC",
  "CIP12CERT1",
  "CIP13CERT2",
  "CIP14CERT1",
  "CIP14BACHL",
  "CIP16CERT1",
  "CIP16BACHL",
  "CIP22CERT1",
  "CIP22BACHL",
  "CIP23BACHL",
  "CIP24BACHL",
  "CIP26CERT2",
  "CIP27CERT2",
  "CIP29BACHL",
  "CIP30CERT2",
  "CIP31BACHL",
  "CIP38BACHL",
  "CIP40CERT2",
  "CIP40BACHL",
  "CIP42CERT2",
  "CIP42BACHL",
  "CIP44BACHL",
  "CIP45CERT2",
  "CIP50CERT2",
  "CIP50CERT4",
  "CIP51CERT1",
  "CIP52CERT1",
  "CIP52ASSOC",
  "CIP52BACHL",
  "CIP54BACHL",
  "SCHTYPE",
  "OPEFLAG",
  "ADMCON7"
)

# Convert all specified variables to factors
data_top100_filtered[vars_to_factor] <- lapply(data_top100_filtered[vars_to_factor], factor)

```


```{r}
# remove 2025 data from training data
training <- data_top100_filtered %>%
  filter(Year != 2025)

testing <- data_top100_filtered %>%
  filter(Year == 2025)

ranking_training <- ranking100 %>%
  select(c("IPEDS.ID", "X2024", "X2023", "X2022", "X2021"))

# pivot ranking
ranking_long <- ranking_training %>% 
  pivot_longer(cols = c(X2024, X2023, X2022, X2021), 
               names_to = "Year",
               values_to = "Ranking"
              )

# fix year variable to represent number
ranking_join <- ranking_long %>%
  mutate(Year = as.numeric(substring(Year, 2)),
         IPEDS.ID = as.numeric(IPEDS.ID))

# merge data and ranking
training <- training %>%
  mutate(UNITID = as.numeric(UNITID))

training_final <- left_join(training, ranking_join, by = c("UNITID" = "IPEDS.ID", "Year" = "Year")) %>% na.omit(Ranking)

training_final$Ranking <- as.numeric(training_final$Ranking)

training_final <- training_final %>% 
  na.omit(Ranking)

# check how many is NA
# sum(is.na(training_final$Ranking))

# religious affiliation because most are NA and not quantitative

training <- subset(training_final, select = -c(Ranking, UNITID, Year, OPEID, OPEID6, INSTNM, CITY, STABBR, ZIP, LONGITUDE, LATITUDE, RELAFFIL, X))

training_matrix <- data.matrix(training)
```

```{r}
# making testing dataset

ranking_testing <- ranking100 %>%
  select(c("IPEDS.ID", "X2025")) %>%
  mutate(X2025 = as.numeric(X2025), IPEDS.ID = as.numeric(IPEDS.ID))

testing <- testing %>%
  mutate(UNITID = as.numeric(UNITID))

testing_final <- left_join(testing, ranking_testing, by = c("UNITID" = "IPEDS.ID"))
```

```{r}
# Run lasso
cv.lasso <- cv.glmnet(training_matrix, training_final$Ranking, alpha=1)  # alpha=1 for Lasso
plot(cv.lasso)

best.lambda <- cv.lasso$lambda.min

lasso.model <- glmnet(training_matrix, training_final$Ranking, alpha=1, lambda=best.lambda)
lasso_select <- coef(lasso.model)

# print(lasso_select)

selected_vars <- rownames(lasso_select)[which(lasso_select != 0)][-1]

# print selected variables
print(selected_vars)

# 110 variables chosen
```


```{r}
# further variable selection

lasso_filtered <- training_final %>%
  select(c(all_of(selected_vars), Ranking))

# backwards selection
back_models <- regsubsets(Ranking~., data = lasso_filtered, nvmax = 30, method = "backward")
summary_back <- summary(back_models)

# save optimal model based on bic
best_model_back <- summary_back$which[which.min(summary_back$bic),]
models_backward <- summary_back$which


```




```{r}
# forward selection
forw_models <- regsubsets(Ranking~., data = lasso_filtered, nvmax = 30, method = "forward")
summary_forw <- summary(forw_models)

# save optimal model based on bic
best_model_forw <- summary_forw$which[which.min(summary_forw$bic),]
models_forward <- summary_forw$which
```

```{r}
# stepwise selection

step_models <- regsubsets(Ranking~., data = lasso_filtered, nvmax = 30, method = "seqrep")
summary_step <- summary(step_models)

# save optimal model based on bic
best_model_step <- summary_step$which[which.min(summary_step$bic),]

# they dropped the factor variable itself, but added the factored variable name with the value string attached back to the formula, which the function doesn't recognize

# check which variables are newly created and add back
missing_vars <- setdiff(selected_vars, colnames(lasso_filtered))
print(missing_vars)

# remove them (and intercept) and add original variable back
step_selected_vars <- names(which(best_model_step))[-c(1, 2, 3, 4, 5, 6)]
step_selected_vars <- c(step_selected_vars, "LOCALE", "CIP15BACHL", "CIP39BACHL", "CIP50BACHL")
which(step_selected_vars == "CIP15BACHL1") 
which(step_selected_vars == "CIP39BACHL1")
which(step_selected_vars == "CIP50BACHL1")

# refit model with selected variables
formula <- as.formula(paste("Ranking ~", paste(step_selected_vars, collapse = " + ")))
final_model_step <- lm(formula, data = lasso_filtered)

# check model performance
summary(final_model_step)

# predict, round, and print
predictions_step <- predict(final_model_step, newdata = testing[, step_selected_vars])
predictions_step_rounded <- sapply(predictions_step, function(x) round(x))
print(predictions_step_rounded)

# calculate accuracy
residual <- {}
for (i in 1:50) {
  residual[i] <-  abs(predictions_step_rounded[i] - testing_final$X2025[i])
}
sum(residual) / 100
```

```{r}
# compare variables from 3 subset selection
vars_each_model <- list(
  backward = names(which(best_model_back)),
  forward = names(which(best_model_forw)),
  stepwise = names(which(best_model_step))
)

vars_each_model

# common
common_vars <- Reduce(intersect, vars_each_model)

# unique
unique_to_backward <- setdiff(vars_each_model$backward, union(vars_each_model$forward, vars_each_model$stepwise))
unique_to_forward <- setdiff(vars_each_model$forward, union(vars_each_model$backward, vars_each_model$stepwise))
unique_to_stepwise <- setdiff(vars_each_model$stepwise, union(vars_each_model$backward, vars_each_model$forward))

list(
  common = common_vars,
  unique_backward = unique_to_backward,
  unique_forward = unique_to_forward,
  unique_stepwise = unique_to_stepwise
)

# compare BIC
min(summary_back$bic)   
min(summary_forw$bic)   
min(summary_step$bic)  
#sequential (step) has lowest BIC

```

```{r}
# best subset selection with sequential variables
  
step_filtered <- training_final %>%
  select(c(all_of(step_selected_vars), Ranking))

# dataframe with only selected 30 variables

best_subset <- regsubsets(Ranking ~ ., data = step_filtered, nvmax = 30) 
summary_best <- summary(best_subset)

#number of variables with smallest BIC is 30
best_model_subset <- which.min(summary_best$bic)


```

